# Generated by Django 4.1.3 on 2024-03-20 21:14

import logging
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import migrations

logger = logging.getLogger('django')

User = get_user_model()

SU_USERNAME = 'admin'
SU_PASSWORD = 'GoBlue!'


def create_development_superuser(apps, schema_editor):
    if settings.ENVIRONMENT == 'development':
        superuser = User.objects.create_superuser(
            username=SU_USERNAME, password=SU_PASSWORD, email=None)
        logger.info('Superuser {superuser} created'.format(superuser=superuser))
    else:
        logger.info('Superuser not created in {env} environment'.format(env=settings.ENVIRONMENT))


def delete_development_superuser(apps, schema_editor):
    superuser = User.objects.filter(username=SU_USERNAME).first()
    if superuser:
        logger.info('Deleting superuser {superuser}'.format(superuser=superuser))
        superuser.delete()
    else:
        logger.info('Superuser not found, did not delete'.format(env=settings.ENVIRONMENT))


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_development_superuser, delete_development_superuser),
    ]
